/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardLandlordRouteImport } from './routes/dashboard.landlord'
import { Route as DashboardEditIdRouteImport } from './routes/dashboard.edit.$id'

const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandlordRoute = DashboardLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/properties'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/tenant'
    | '/properties/$id'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/properties'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/tenant'
    | '/properties/$id'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/properties'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/tenant'
    | '/properties/$id'
    | '/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landlord': {
      id: '/dashboard/landlord'
      path: '/landlord'
      fullPath: '/dashboard/landlord'
      preLoaderRoute: typeof DashboardLandlordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit/$id': {
      id: '/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof DashboardEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardLandlordRoute: typeof DashboardLandlordRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  DashboardEditIdRoute: typeof DashboardEditIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLandlordRoute: DashboardLandlordRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  DashboardEditIdRoute: DashboardEditIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
