/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardRemindersRouteImport } from './routes/dashboard.reminders'
import { Route as DashboardReceiptsRouteImport } from './routes/dashboard.receipts'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardLandlordRouteImport } from './routes/dashboard.landlord'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as BlogRentalIncomeTaxKenyaRouteImport } from './routes/blog.rental-income-tax-kenya'
import { Route as DashboardReceiptsIdRouteImport } from './routes/dashboard.receipts.$id'
import { Route as DashboardEditIdRouteImport } from './routes/dashboard.edit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReceiptsRoute = DashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandlordRoute = DashboardLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogRentalIncomeTaxKenyaRoute =
  BlogRentalIncomeTaxKenyaRouteImport.update({
    id: '/blog/rental-income-tax-kenya',
    path: '/blog/rental-income-tax-kenya',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardReceiptsIdRoute = DashboardReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardReceiptsRoute,
} as any)
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rental-income-tax-kenya': typeof BlogRentalIncomeTaxKenyaRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/receipts': typeof DashboardReceiptsRouteWithChildren
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
  '/dashboard/receipts/$id': typeof DashboardReceiptsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rental-income-tax-kenya': typeof BlogRentalIncomeTaxKenyaRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/receipts': typeof DashboardReceiptsRouteWithChildren
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
  '/dashboard/receipts/$id': typeof DashboardReceiptsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rental-income-tax-kenya': typeof BlogRentalIncomeTaxKenyaRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/receipts': typeof DashboardReceiptsRouteWithChildren
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
  '/dashboard/receipts/$id': typeof DashboardReceiptsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/properties'
    | '/sitemap.xml'
    | '/blog/rental-income-tax-kenya'
    | '/dashboard/account'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/receipts'
    | '/dashboard/reminders'
    | '/dashboard/tenant'
    | '/onboarding/role'
    | '/properties/$id'
    | '/dashboard/'
    | '/dashboard/edit/$id'
    | '/dashboard/receipts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/properties'
    | '/sitemap.xml'
    | '/blog/rental-income-tax-kenya'
    | '/dashboard/account'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/receipts'
    | '/dashboard/reminders'
    | '/dashboard/tenant'
    | '/onboarding/role'
    | '/properties/$id'
    | '/dashboard'
    | '/dashboard/edit/$id'
    | '/dashboard/receipts/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/properties'
    | '/sitemap.xml'
    | '/blog/rental-income-tax-kenya'
    | '/dashboard/account'
    | '/dashboard/landlord'
    | '/dashboard/new'
    | '/dashboard/receipts'
    | '/dashboard/reminders'
    | '/dashboard/tenant'
    | '/onboarding/role'
    | '/properties/$id'
    | '/dashboard/'
    | '/dashboard/edit/$id'
    | '/dashboard/receipts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogRentalIncomeTaxKenyaRoute: typeof BlogRentalIncomeTaxKenyaRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reminders': {
      id: '/dashboard/reminders'
      path: '/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receipts': {
      id: '/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof DashboardReceiptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landlord': {
      id: '/dashboard/landlord'
      path: '/landlord'
      fullPath: '/dashboard/landlord'
      preLoaderRoute: typeof DashboardLandlordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/rental-income-tax-kenya': {
      id: '/blog/rental-income-tax-kenya'
      path: '/blog/rental-income-tax-kenya'
      fullPath: '/blog/rental-income-tax-kenya'
      preLoaderRoute: typeof BlogRentalIncomeTaxKenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/receipts/$id': {
      id: '/dashboard/receipts/$id'
      path: '/$id'
      fullPath: '/dashboard/receipts/$id'
      preLoaderRoute: typeof DashboardReceiptsIdRouteImport
      parentRoute: typeof DashboardReceiptsRoute
    }
    '/dashboard/edit/$id': {
      id: '/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof DashboardEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardReceiptsRouteChildren {
  DashboardReceiptsIdRoute: typeof DashboardReceiptsIdRoute
}

const DashboardReceiptsRouteChildren: DashboardReceiptsRouteChildren = {
  DashboardReceiptsIdRoute: DashboardReceiptsIdRoute,
}

const DashboardReceiptsRouteWithChildren =
  DashboardReceiptsRoute._addFileChildren(DashboardReceiptsRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardLandlordRoute: typeof DashboardLandlordRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardReceiptsRoute: typeof DashboardReceiptsRouteWithChildren
  DashboardRemindersRoute: typeof DashboardRemindersRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditIdRoute: typeof DashboardEditIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardLandlordRoute: DashboardLandlordRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardReceiptsRoute: DashboardReceiptsRouteWithChildren,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditIdRoute: DashboardEditIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogRentalIncomeTaxKenyaRoute: BlogRentalIncomeTaxKenyaRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
